### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by iamsiddharthdas** [subhadeepdan/Secure-File-Storage-using-Hybrid-Cryptography#1]
Shows 404 error after the registration page. I think the SQL files are not uploaded.
Please check the issue involved and resolve it at the earliest

**Comment by C-VEDIYAPPAN** [comment]
i will facing error.after registration page it will show 404 error

**Comment by C-VEDIYAPPAN** [comment]
i need help. because i'll take this project final year

**Comment by mvimal2607** [comment]
> commented

Bro project run?

**Comment by mvimal2607** [comment]
> i need help. because i'll take this project final year

I got error in registeration form
